# Generated by Django 4.2.1 on 2023-06-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autopark", "0005_alter_booking_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="last_maintenance_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="next_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
